# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microplane < Formula
  desc "The control plane for localhost."
  homepage "https://microplane.dev/"
  version "0.0.4"

  on_macos do
    url "https://github.com/segiddins/microplane/releases/download/v0.0.4/microplane_Darwin_all.tar.gz"
    sha256 "20d139933f48d27eeab30344c77c27860821273be36c593b69254a16cc0318b8"

    def install
      # keep the other lines here
      # TODO: replace your-cli with your binary name
      man1.install "manpages"
      # keep the other lines here
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/segiddins/microplane/releases/download/v0.0.4/microplane_Linux_arm64.tar.gz"
      sha256 "f7cfbce445c29434365567140218b842c645db0b105c00b482c7e595c27dcee5"

      def install
        # keep the other lines here
        # TODO: replace your-cli with your binary name
        man1.install "manpages"
        # keep the other lines here
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/segiddins/microplane/releases/download/v0.0.4/microplane_Linux_x86_64.tar.gz"
      sha256 "d26ee0a5cac8e0c20a3aee7a141b7e69a3ab0f5b7b8aeb1b6181909c01b16f63"

      def install
        # keep the other lines here
        # TODO: replace your-cli with your binary name
        man1.install "manpages"
        # keep the other lines here
      end
    end
  end

  def caveats
    <<~EOS
      Check out microplane.dev to subscribe and unlock all of microplane's pro features,
      including unlimited concurrent applications, and more to come!
    EOS
  end
end
