# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microplane < Formula
  desc "The control plane for localhost."
  homepage "https://microplane.dev/"
  version "0.0.9"

  on_macos do
    url "https://github.com/nerdsniped/microplane/releases/download/v0.0.9/microplane_Darwin_all.tar.gz"
    sha256 "b87b99b2c5a971e627251ff962f9da3ab247b8ea8760c75a3acf40cb9ce6c94e"

    def install
      bin.install "microplane"
      man1.install "manpages"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nerdsniped/microplane/releases/download/v0.0.9/microplane_Linux_arm64.tar.gz"
      sha256 "fe9ece7d5b720e47923ee1402984e0f35adfd5030aef7da1dbffc6fb1ed4957a"

      def install
        bin.install "microplane"
        man1.install "manpages"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nerdsniped/microplane/releases/download/v0.0.9/microplane_Linux_x86_64.tar.gz"
      sha256 "61edc9809438f1f5c78157530e0ee9c928cb93c55a2d43d246ec3b138c91afb2"

      def install
        bin.install "microplane"
        man1.install "manpages"
      end
    end
  end

  def caveats
    <<~EOS
      Check out microplane.dev to subscribe and unlock all of microplane's pro features,
      including unlimited concurrent applications, and more to come!
    EOS
  end
end
